# frontend/Dockerfile.frontend
FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm i

COPY . .
EXPOSE 5173

# Vite dev server accesible desde host
CMD ["npm","run","dev","--","--host","0.0.0.0"]
